### ISSUE TITLE
how to build restclient-cpp on windows platforms ?

### ISSUE THREAD

**Issue by how0723** [mrtazz/restclient-cpp#101]
how to build restclient-cpp on windows platforms ?
such as win10

**Comment by how0723** [comment]
@ghabxph  yes. it can work on windows platforms. i have build it successfully.

**Comment by mrtazz** [comment]
thanks for confirming!

**Comment by muhaye** [comment]
@mrtazz I'm having some trouble cross-compiling 
./configure --host=x86_64-w64-mingw32 


1) was expecting to get some  librestclient_cpp.dll.a, but just 
librestclient-cpp.a
librestclient-cpp.la -> ../librestclient-cpp.la
librestclient-cpp.lai 

I get these error:

librestclient-cpp.a(librestclient_cpp_la-restclient.o):restclient.cc:(.text+0x10): undefined reference to `__imp_curl_global_init' ...

Any help willl be appreciate

**Comment by tyler-chang** [comment]
@how0723 Can you share how to build that on windows? Thank you.
