### ISSUE TITLE
Cannot locate restclient-cpp/version.h

### ISSUE THREAD

**Issue by pupesko** [mrtazz/restclient-cpp#113]
### Expected behaviour
expected to automatically include version.h when after including restclient-cpp/restclient.h into the project.
### Actual behaviour
It throws an error when building the project which says that there is no such file or directory as "restclient-cpp/version.h"
### Environment and debugging details
I am working on Linux, ubuntu version, coding in Eclipse 
- compiler and version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
- operating system
Ubuntu
### What I tried doing
The way I started setting it up is by downloading the zip file from github containing all the files. Then in Eclipse I set a path to the folders that contain the header files and source files respectively. Afterwards I included "restclient-cpp/restclient.h" in the Main.cpp file of my project. after building the project however, it threw the above error. In the restclient-cpp folder I couldn't find any version.h file and I see that the restclient.h includes restclient-cpp/version.h. 

In the end, I checked the installation guide and followed the steps, downloaded and installed the proper package for my OS but I'm not sure what to do with them now.

**Comment by mrtazz** [comment]
You can either make sure your build process calls the [make target for building the version](https://github.com/mrtazz/restclient-cpp/blob/master/Makefile.am#L21). However that relies on having a full git checkout of the repo as the version is driven off of git tags. It's easier to use a [pre-build package](https://packagecloud.io/mrtazz/restclient-cpp) if you can and include that in your build as you would with any other library.
