### ISSUE TITLE
std:prt_fun is removed in c++17

### ISSUE THREAD

**Issue by murillo128** [mrtazz/restclient-cpp#122]
### Expected behaviour
compile with c++17

### Actual behaviour
doesn't compile
restclient-cpp/helpers.h(56): error C2039: 'ptr_fun': is not a member of 'std'

### Environment and debugging details
msvc 17/windows 10

https://en.cppreference.com/w/cpp/utility/functional/ptr_fun

**Comment by mrtazz** [comment]
work to address this is happening in https://github.com/mrtazz/restclient-cpp/pull/127

**Comment by mrtazz** [comment]
closed via https://github.com/mrtazz/restclient-cpp/pull/127
