### ISSUE TITLE
How to set certificates on a Windows machines using conn

### ISSUE THREAD

**Issue by jelizaga3-gatech** [mrtazz/restclient-cpp#129]
I am using a Windows 10 machine with Visual Studio to compile a project using Curl as a dependency. 

My file structure is:

    |- Debug
        |-cacert.pem
        |-libcrypto-1_1-x64.dll
        |-libcurl-x64.dll
        |-libssl-1_1-x64
        |-testDriver.exe
        |-testDriver.ilk
        |-testDriver.pdb

When running the following code
```
RestClient::Connection* conn = new RestClient::Connection("https://url.com");
conn->SetCAInfoFilePath(R"(cacert.pem)");
conn->SetCertPath(R"(cacert.pem)");
conn->SetCertType("PEM");
RestClient::Response r = conn->get("");
```

After executing this line, 
https://github.com/mrtazz/restclient-cpp/blob/ec6bce5028f7cc265f864b87a1a4f59adfa3a91b/source/connection.cc#L399

I receive the following error value for `res = CURLE_SSL_CERTPROBLEM (58)`

I downloaded my cacert.pem from here https://curl.haxx.se/docs/caextract.html

Any guidance as to what I need to do on my Windows machine to get res = CURLE_OK (0)?

**Comment by jelizaga3-gatech** [comment]
Oof -

`The CURLOPT_CAPATH function apparently does not work in Windows due to some limitation in openssl.`

https://curl.haxx.se/libcurl/c/CURLOPT_CAPATH.html

**Comment by mrtazz** [comment]
There is no workaround to my knowledge. Closing this since it's a problem with curl/openssl rather than restclient
