### ISSUE TITLE
 Can you add an example of downloading a file?

### ISSUE THREAD

**Issue by xiaonaiquan** [mrtazz/restclient-cpp#137]
Can you add an example of downloading a file?

**Comment by tastytea** [comment]
Just write the body to a file.

``` c++
#include "restclient-cpp/restclient.h"
#include <fstream>

int main()
{
    RestClient::Response r = RestClient::get("http://example.com/");
    std::ofstream file("example.html", std::ios::binary);
    file.write(r.body.c_str(), r.body.size());
}
```

**Comment by xiaonaiquan** [comment]
> Just write the body to a file.
> 
> ```c++
> #include "restclient-cpp/restclient.h"
> #include <fstream>
> 
> int main()
> {
>     RestClient::Response r = RestClient::get("http://example.com/");
>     std::ofstream file("example.html", std::ios::binary);
>     file.write(r.body.c_str(), r.body.size());
> }
> ```

thanks
