### ISSUE TITLE
Debian package: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_3'

### ISSUE THREAD

**Issue by tastytea** [mrtazz/restclient-cpp#144]
It seems the shared library in the Debian buster package is built against libcurl3, which is not available in Debian buster.

### Source code

``` c++
#include <restclient-cpp/restclient.h>

int main()
{
    RestClient::Response r = RestClient::get("https://example.com");
}
```

#### Compile flags

```shellsession
$ g++ --std=c++14 -lrestclient-cpp $(pkg-config --libs --cflags libcurl) -lpthread test.cpp
```

### Actual behaviour

```
/usr/bin/ld: /tmp/ccSW6rEE.o: in function `main':
test.cpp:(.text+0x41): undefined reference to `RestClient::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_3'
```

… and so on.

### `ldd` output

``` shellsession
$ ldd /usr/lib/librestclient-cpp.so
/usr/lib/librestclient-cpp.so: /lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/lib/librestclient-cpp.so)
```

### Environment and debugging details

- compiler and version
  - **g++ (Debian 8.3.0-6) 8.3.0**
- operating system
  - **Debian 10 (buster)**
- version of restclient-cpp
  - **0.5.1-1**
- how did you install restclient-cpp? (via packages, git, tarball)
  - **Debian package for buster amd64**
- libcurl version and compile flags
  - **Debian package libcurl4, version 7.64.0-4**
- full error output of your build as an inline codeblock or gist
```
/usr/bin/ld: /tmp/ccejRJkF.o: in function `main':
test.cpp:(.text+0x41): undefined reference to `RestClient::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_slist_free_all@CURL_OPENSSL_3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_easy_perform@CURL_OPENSSL_3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_slist_append@CURL_OPENSSL_3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_global_init@CURL_OPENSSL_3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_easy_init@CURL_OPENSSL_3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_easy_strerror@CURL_OPENSSL_3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_easy_reset@CURL_OPENSSL_3'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/librestclient-cpp.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_3'
collect2: error: ld returned 1 exit status
```

**Comment by watsocd** [comment]
This is how I compiled on Buster to resolve this issue.

g++ main.c restclient.cc connection.cc helpers.cc -o main -lcurl

I am not a C expert but I believe I am recompiling the entire library. I know this works.

**Comment by tastytea** [comment]
Yes, it works when I compile it myself, but I was planning to release a Debian package of my program which depends on the Debian package for restclient-cpp…

**Comment by tastytea** [comment]
[It seems](https://travis-ci.org/mrtazz/restclient-cpp/jobs/528769350#L1643) that all `.deb` packages are the same, built on Ubuntu trusty. That's not going to work, the different distributions have different versions of libcurl in their repositories. [Debian jessie and stretch have libcurl3](https://packages.debian.org/search?keywords=libcurl3) and [Debian buster and bullseye have libcurl4](https://packages.debian.org/search?keywords=libcurl4), for example.

**Comment by tastytea** [comment]
The package [libcurl4-openssl-dev in Ubuntu trusty (14.04)](https://launchpad.net/ubuntu/trusty/amd64/libcurl4-openssl-dev/7.35.0-1ubuntu2.20) depends on `libcurl3`. In [Ubuntu bionic (18.04)](https://packages.ubuntu.com/bionic/libcurl4-openssl-dev) it depends on `libcurl4`. Could you build the packages for Debian <= stretch and Ubuntu <= xenial on trusty and the packages for Debian >=buster and Ubuntu >= bionic on bionic?

 #116 is related.

**Comment by mrtazz** [comment]
oh thanks for investigating this. I'm not a Debian/Ubuntu user, so these package builds currently reflect the simplest thing I thought could work.

I'll review some options to get automated package builds that are created on the correct platforms. If you have any input/experience on this, suggestions are very appreciated.

**Comment by tastytea** [comment]
I think it should work when you build the packages for Debian *jessie*, *stretch* and *buster* and Ubuntu *trusty* and *xenial* on [xenial](https://docs.travis-ci.com/user/reference/xenial/) or [trusty](https://docs.travis-ci.com/user/reference/trusty/) and the packages for Debian *buster* and Ubuntu *bionic* on [bionic](https://docs.travis-ci.com/user/reference/bionic/), but I haven't tried it.

I don't know about Debian wheezy, but since it doesn't get updates [since 2018-05-31](https://wiki.debian.org/LTS), I think it can be safely dropped.
