### ISSUE TITLE
Release a new tag ?

### ISSUE THREAD

**Issue by Milerius** [mrtazz/restclient-cpp#145]
Is it possible to release a new tag for people that use rest client through VCPKG ? There is no new tag since May !

**Comment by et-nik** [comment]
No great need for new tags.
You can use commit hashes instead of tags in VCPKG.

Open file `ports/restclient-cpp/portfile.cmake` and replace `REF 0.5.1` to some hash, eg last commit:
```
vcpkg_from_github(
    ...
    REF 6336cae5275c9aeddf99f13c49e8f9320f7ca4bc
    ...
)
```

**Comment by Milerius** [comment]
anyway the Vcpkg port doesn't work on OSX/Linux :/

**Comment by et-nik** [comment]
I guess It is vcpkg port config bug. Need to fix and send PR to vcpkg.
I made some changes on my vcpkg fork https://github.com/et-nik/vcpkg/tree/master/ports/restclient-cpp
