### ISSUE TITLE
A little question: Is this lib thread safe?

### ISSUE THREAD

**Issue by SimonZgx** [mrtazz/restclient-cpp#147]
I'm tring to build my trading bot using this lib. I've add a thread pool base on the lib to reuse the connection,  but I don't konw much about `libcurl`.

I'd appreciate if anyone could answer my question as the title says.

**Comment by tastytea** [comment]
have you seen <https://github.com/mrtazz/restclient-cpp#thread-safety>?

**Comment by SimonZgx** [comment]
Ah,I see. Thank you Sir!
