### ISSUE TITLE
Includes Error

### ISSUE THREAD

**Issue by Spottimus** [mrtazz/restclient-cpp#15]
- I had errors while trying to start using restclient-cpp within my own project due to missing includes. These are all the includes required to work for me.

```
#include <libcurl\curl.h>
#include <string>
#include <map>
#include <cstdlib>
#include "meta.h"
#include <algorithm>
#include <iostream>
#include <functional>
#include <locale>
#include <numeric>
#include <cctype>
```

**Comment by salehi** [comment]
You have to give more information about the error in order to we can understand what is your problem.
paste the output in a paste service or Gist and link it here.

**Comment by mrtazz** [comment]
I second what @salehi said. Could you please provide more information about what the problem is here? A gist of example code and the error would be great.

**Comment by salehi** [comment]
@mrtazz Forget it, I just suggested him to be better reporter :)

**Comment by mrtazz** [comment]
Closing this for now. If the problem persists, please reopen with a more detailed error description and some debug output.
