### ISSUE TITLE
libcurl.so

### ISSUE THREAD

**Issue by YanMario** [mrtazz/restclient-cpp#152]
librestclient-cpp.so：对‘curl_easy_perform’未定义的引用
librestclient-cpp.so：对‘curl_easy_getinfo’未定义的引用
librestclient-cpp.so：对‘curl_easy_reset’未定义的引用

**Comment by mrtazz** [comment]
can you please add some context around what the problem is and what error message you're seeing in English?

**Comment by mrtazz** [comment]
Closing this for lack of details about the problem. Please feel free to reopen if you can provide more information.

**Comment by YanMario** [comment]
Ok,Thank you, I resolve it.


| |
13279406510
|
|
13279406510@163.com
|
签名由网易邮箱大师定制


On 03/19/2020 02:47，Daniel Schauenberg<notifications@github.com> wrote：

Closing this for lack of details about the problem. Please feel free to reopen if you can provide more information.
