### ISSUE TITLE
add custom / additional header fields

### ISSUE THREAD

**Issue by torbjoernk** [mrtazz/restclient-cpp#18]
I'd like to use this little library in a toy project of mine. However, I couldn't find a way to add additional header fields to any of the REST method calls.

Is it planned to support that in the near future? What about the HEAD method? Are you going to support this too?

**Comment by drjasonharrison** [comment]
@torbjoernk You can use the ctype parameter to add additional headers, it was intended to be used for the Content-Type header but if you can append a newline and more headers:
    std::string headers = std::string( "application/x-www-form-urlencoded\n" ) 
                                     + "Authorization: Bearer " + m_authorizationToken;
    RestClient::response r = RestClient::post( url, headers, data );

**Comment by torbjoernk** [comment]
That seems a little hackish, but better than nothing. I'll see whether I'll come up with a better solution to send you as a PR.
