### ISSUE TITLE
librestclient-cpp.so

### ISSUE THREAD

**Issue by LJZ458** [mrtazz/restclient-cpp#191]
Hi, i'm installing SpecTcl which has a dependence of restclient-cpp. However, it needs librestclient-cpp.so but i couldnt find it in any folders. Is there other ways to create this share files?

![Screenshot from 2023-06-22 14-37-48](https://github.com/mrtazz/restclient-cpp/assets/104240462/a40f28e7-324c-4d60-9729-8fb5a41e491e)

**Comment by rfoxkendo** [comment]
Just came across this

This is something I think us guys at the FRIB might be able to help you with better.  Perhaps better to file this issue with 
github.com/FRIBDAQ/SpecTcl  we can also share a general help desk ticket email that I'm reluctant to post here for obvious reasons.

however what you need to do is download the restclient-cpp package here - build it and use the --with-restclient-cpp option to point to the top level directory in which you installed restclient-cpp

what you are seeing here is a source code repository for librestclient-cpp not a binary distribution so you'll need to build the shared object yourself.

restclient-cpp repostory kings - you can probably close this issue as it's really adressed to us.

Ron Fox
Senior Scientist
Facility for Rare Isotope Beams
Michigan State University
640 South Shaw Lane
