### ISSUE TITLE
Memory leak on Fail to query/No response

### ISSUE THREAD

**Issue by watsocd** [mrtazz/restclient-cpp#21]
I found another memory leak in restclient.cpp.

If the remote server does not respond to the request, line 223 returns from the PUT function before doing the CURL cleanups on lines 229 thru 231. This causes a memory leak.

I tested the following code change and it resolves the leak. This same issue is elsewhere in the file as well.

if (res != CURLE_OK)
    {
      ret.body = "Failed to query.";
      ret.code = -1;
      //return ret; //Commented the return
    } else {  //else added here
      long http_code = 0;
      curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
      ret.code = static_cast<int>(http_code);
     }

Function now has only one return statement.

**Comment by mrtazz** [comment]
closing this, since the discussion basically moved to #22
