### ISSUE TITLE
curl_global_cleanup at the end of every request is harmful

### ISSUE THREAD

**Issue by juhanima** [mrtazz/restclient-cpp#29]
The following was observed in AOSP. Calling curl_global_cleanup at the end of every request is harmful, because it cleans up OpenSSL's internal algorithm directory by EVP_Cleanup, effectively undoing OpenSSL_add_all_algorithms(). If OpenSSL is used between requests, for instance certificate vaildation fails with a signature error 7 since the library cannot lookup for algorithms. I would suggest removing the curl_global_cleanup call as AFAIK it's not really needed.

**Comment by mrtazz** [comment]
thanks for the issue report! this is fixed now in master with https://github.com/mrtazz/restclient-cpp/commit/c467955d6f81375d15e2c8be2dc2f51b150f1315
