### ISSUE TITLE
support for persisten connection and connection pool

### ISSUE THREAD

**Issue by silviucpp** [mrtazz/restclient-cpp#31]
Hello the project is very nice but I don't see support for persistent connections (send multiple requests over the same connection) and also support for a connection pool.

**Comment by mrtazz** [comment]
This is a good idea. I think in it's current state it depends on https://github.com/mrtazz/restclient-cpp/issues/27 as libcurl achieves persistent connections and pooling via request done with the same handle (http://curl.haxx.se/docs/faq.html#What_about_Keep_Alive_or_persist). So once I find some time to fix #27 this should be possible. I'll definitely keep this issue in mind when working on the usability improvements.

**Comment by mrtazz** [comment]
implemented with https://github.com/mrtazz/restclient-cpp/pull/39
