### ISSUE TITLE
Add method to set user-agent

### ISSUE THREAD

**Issue by mheffner** [mrtazz/restclient-cpp#33]
Add a method to set a custom user agent. This could prepend a custom agent onto the existing restclient-cpp user agent, eg `User-Agent: foobar/1.2.3 restclient-cpp/2.0.0`.

This is useful when building a custom reporter on top of a REST client API.

**Comment by mrtazz** [comment]
punting this one to [v0.4.0](https://github.com/mrtazz/restclient-cpp/milestones/v0.4.0) so I can cut [v0.3.0](https://github.com/mrtazz/restclient-cpp/milestones/v0.3.0) as an intermediary release featuring all the things that have gone in so far before I embark on some refactoring for https://github.com/mrtazz/restclient-cpp/issues/27.

**Comment by mrtazz** [comment]
implemented with https://github.com/mrtazz/restclient-cpp/pull/39
