### ISSUE TITLE
built .so can be linked to libgtest.so

### ISSUE THREAD

**Issue by tgoetze** [mrtazz/restclient-cpp#34]
I think the libgtest.so should only be built into the test_program and not the shared object, since it is not used at runtime.
From looking at the Makefile.am, it looks like ```-lgtest``` is included in the test_program in all cases, so I believe a simple fix is to just remove the line
```AC_CHECK_LIB([gtest], [main])```
from the configure.ac

Does this sound reasonable?

**Comment by tgoetze** [comment]
Note that I said "can be" in the title, since the current build process actually does not seem to use the included gtest code. I discovered this issue, since when I built locally (and did not have gtest RPMs installed) my restclient-cpp.so did not reference libgtest.so. However, when the build server built it, it found gtest RPMs, so the build systems restclient-cpp.so had a reference to libtest.so (which is not what I want).

**Comment by mrtazz** [comment]
fixed with #35
