### ISSUE TITLE
Could the lib support https urls?

### ISSUE THREAD

**Issue by tonysongtl** [mrtazz/restclient-cpp#47]

**Comment by tgoetze** [comment]
The https support is handled by libcurl and as long as your libcurl was compiled with openssl support, you should have support for https URLs that have are trusted by your system. If you need to tell libcurl which certificates should be trusted, there is a pull request #44 that is available to allow restclient-cpp to pass that information along to libcurl.

**Comment by mrtazz** [comment]
yup! the lib supports https. The tests itself are actually run against https as well https://github.com/mrtazz/restclient-cpp/blob/master/test/test_connection.cc#L24

**Comment by tonysongtl** [comment]
That's greate. Thanks.

**Comment by SandaTong** [comment]
hi mrtazz~ i tried to post a request with https url, but i got a error return from curl which return code is CURLE_SSL_CONNECT_ERROR（35） i wonder whether some settings i need to set when i want to use https url ?

**Comment by mrtazz** [comment]
@SandaTong can you please add the example code you used and the platform (OS version, compiler version, etc) you are running on?

**Comment by SandaTong** [comment]
@mrtazz  hi~mrtazz, i tried to post my url using RestClient::post() method , but i got the return error in performCurlRequest() method , and here is a part of code where it returns to me
`  res = curl_easy_perform(this->curlHandle);
  if (res != CURLE_OK) {
    if (res == CURLE_OPERATION_TIMEDOUT) {
      ret.code = res;
      ret.body = "Operation Timeout.";
    } else {
      ret.body = "Failed to query.";
      ret.code = -1;
    }
  } else {
    int64_t http_code = 0;
    curl_easy_getinfo(this->curlHandle, CURLINFO_RESPONSE_CODE, &http_code);
    ret.code = static_cast<int>(http_code);
  }`
i got the ret code is CURLE_SSL_CONNECT_ERROR, and ret body is "Failed to query"
also i tried to disable ssl type verify and host verify, and it doesn't work either, here is my disable code ssl code 
` curl_easy_setopt(this->curlHandle, CURLOPT_SSL_VERIFYPEER, false);
curl_easy_setopt(this->curlHandle, CURLOPT_SSL_VERIFYHOST, false); `
my os version is Windows7 Service Pack1 and RestClient version is "M4_RESTCLIENT_VERSION"
