### ISSUE TITLE
Please add `ldconfig` into `make install` to update cache

### ISSUE THREAD

**Issue by Lw-Cui** [mrtazz/restclient-cpp#48]
I often forget refresh dynamic lib cache, which always makes me feel confused. 
So I think add `ldconfig` directly is good for everyone:)
Thanks!

**Comment by mrtazz** [comment]
I don't think adding this to the `make install` target is a good idea. That target is really supposed to be a plumbing task for the single purpose of installing the library. It is also used in the package build and it doesn't really make sense to have the ldconfig being run there.

However I think it's a great idea to make it easier to not forget about `ldconfig`. So I added a util script to run it and also made it part of the package build. So if you install it via the [Linux packages](https://packagecloud.io/mrtazz/restclient-cpp), `ldconfig` is run.
