### ISSUE TITLE
Curl problem

### ISSUE THREAD

**Issue by JorricksTU** [mrtazz/restclient-cpp#52]
Hello,
I am getting the following error:
`include/restclient-cpp/restclient.h:12:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>`
Even though I have libcurl3 installed on ubuntu.
Still, this is what I get during configure.
`checking curl/curl.h usability... no
checking curl/curl.h presence... no
checking for curl/curl.h... no`

Could you please provide me some insight, kind of a noob here :$ :)

**Comment by JorricksTU** [comment]
Nvm.. I found out I had to install libcurl-dev. Sorry for the disturbance

**Comment by mrtazz** [comment]
No worries! Let me know if you run into any other problems!
