### ISSUE TITLE
Android NDK Support and iOS support

### ISSUE THREAD

**Issue by vinodshinde** [mrtazz/restclient-cpp#53]
Hi,
Can this be used on Android and iOS apps? Any info on how to build using latest Android NDK and Android studio will be really helpful.
Thanks,

**Comment by mrtazz** [comment]
Hi! I'm unfortunately not an Android or iOS developer so I have no idea how the build tooling looks there or if there is anything blocking this. My guess is that you should at the very least be able to import the source and header files into your project and build them together with your app. Hope that helps a bit!
