### ISSUE TITLE
Compilation on Cygwin does not build shared libraries

### ISSUE THREAD

**Issue by instigatorofawe** [mrtazz/restclient-cpp#55]
Attempting to compile the library on cygwin yields the libtool error:

```
libtool: warning: undefined symbols not allowed in x86_64-unknown-cygwin shared
libraries; building static only
```

Indeed, attempting to compile a program with the library yields a slew of reference not found errors in the vein of:

```
undefined reference to `RestClient::post(std::string const&, std::string const&, 
std::string const&)'
relocation truncated to fit: R_X86_64_PC32 against undefined symbol `RestClient::post(
std::string const&, std::string const&, std::string const&)'
collect2: error: ld returned 1 exit status
```

**Comment by mrtazz** [comment]
can you provide more of the libtool output? does it work if you link the library statically into your program?

**Comment by Absox** [comment]
Here's everything from when i run make:

m4 -I m4 -DM4_RESTCLIENT_VERSION=0.4.4-2-gad96b12-dirty version.h.m4 > include/restclient-cpp/version.h
make  all-am
make[1]: Entering directory '/home/rliu14/Downloads/restclient-cpp'
m4 -I m4 -DM4_RESTCLIENT_VERSION=0.4.4-2-gad96b12-dirty version.h.m4 > include/restclient-cpp/version.h
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.   -Iinclude -fPIC -g -O2 -MT source/librestclient_cpp_la-restclient.lo -MD -MP -MF source/.deps/librestclient_cpp_la-restclient.Tpo -c -o source/librestclient_cpp_la-restclient.lo `test -f 'source/restclient.cc' || echo './'`source/restclient.cc
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.   -Iinclude -fPIC -g -O2 -MT source/librestclient_cpp_la-connection.lo -MD -MP -MF source/.deps/librestclient_cpp_la-connection.Tpo -c -o source/librestclient_cpp_la-connection.lo `test -f 'source/connection.cc' || echo './'`source/connection.cc
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.   -Iinclude -fPIC -g -O2 -MT source/librestclient_cpp_la-helpers.lo -MD -MP -MF source/.deps/librestclient_cpp_la-helpers.Tpo -c -o source/librestclient_cpp_la-helpers.lo `test -f 'source/helpers.cc' || echo './'`source/helpers.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -Iinclude -fPIC -g -O2 -MT source/librestclient_cpp_la-restclient.lo -MD -MP -MF source/.deps/librestclient_cpp_la-restclient.Tpo -c source/restclient.cc  -DDLL_EXPORT -DPIC -o source/.libs/librestclient_cpp_la-restclient.o
 -DPIC -o source/.libs/librestclient_cpp_la-connection.oIC -g -O2 -MT source/librestclient_cpp_la-connection.lo -MD -MP -MF source/.deps/librestclient_cpp_la-connection.Tpo -c source/connection.cc  -DDLL_EXPORT
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -Iinclude -fPIC -g -O2 -MT source/librestclient_cpp_la-helpers.lo -MD -MP -MF source/.deps/librestclient_cpp_la-helpers.Tpo -c source/helpers.cc  -DDLL_EXPORT -DPIC -o source/.libs/librestclient_cpp_la-helpers.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -Iinclude -fPIC -g -O2 -MT source/librestclient_cpp_la-restclient.lo -MD -MP -MF source/.deps/librestclient_cpp_la-restclient.Tpo -c source/restclient.cc -o source/librestclient_cpp_la-restclient.o >/dev/null 2>&1
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -Iinclude -fPIC -g -O2 -MT source/librestclient_cpp_la-helpers.lo -MD -MP -MF source/.deps/librestclient_cpp_la-helpers.Tpo -c source/helpers.cc -o source/librestclient_cpp_la-helpers.o >/dev/null 2>&1
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -Iinclude -fPIC -g -O2 -MT source/librestclient_cpp_la-connection.lo -MD -MP -MF source/.deps/librestclient_cpp_la-connection.Tpo -c source/connection.cc -o source/librestclient_cpp_la-connection.o >/dev/null 2>&1
mv -f source/.deps/librestclient_cpp_la-restclient.Tpo source/.deps/librestclient_cpp_la-restclient.Plo
mv -f source/.deps/librestclient_cpp_la-helpers.Tpo source/.deps/librestclient_cpp_la-helpers.Plo
mv -f source/.deps/librestclient_cpp_la-connection.Tpo source/.deps/librestclient_cpp_la-connection.Plo
/bin/sh ./libtool  --tag=CXX   --mode=link g++ -fPIC -g -O2 -version-info 2:1:1  -o librestclient-cpp.la -rpath /usr/local/lib source/librestclient_cpp_la-restclient.lo source/librestclient_cpp_la-connection.lo source/librestclient_cpp_la-helpers.lo  -lcurl
libtool: warning: undefined symbols not allowed in x86_64-unknown-cygwin shared libraries; building static only
libtool: link: rm -fr  .libs/librestclient-cpp.a .libs/librestclient-cpp.la .libs/librestclient-cpp.lai
libtool: link: ar cru .libs/librestclient-cpp.a  source/librestclient_cpp_la-restclient.o source/librestclient_cpp_la-connection.o source/librestclient_cpp_la-helpers.o
libtool: link: ranlib .libs/librestclient-cpp.a
libtool: link: ( cd ".libs" && rm -f "librestclient-cpp.la" && ln -s "../librestclient-cpp.la" "librestclient-cpp.la" )
make[1]: Leaving directory '/home/rliu14/Downloads/restclient-cpp'

I've tried linking the .a file in /usr/local/lib, but that doesn't seem to work either. It still yields the same "undefined reference" errors.

**Comment by mrtazz** [comment]
It sounds like the configure file is missing a stanza for win32. Can you try adding `win32-dll` to `LT_INIT` as per [1](https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html)?

**Comment by Absox** [comment]
I have LT_INIT([win32-dll]) in my configure.ac
However, I'm still seeing the warning.

**Comment by AronRubin** [comment]
This should be solved with CMake.

**Comment by mrtazz** [comment]
closing this then. @instigatorofawe please reopen if the problem persists
