### ISSUE TITLE
i can't find the version.h

### ISSUE THREAD

**Issue by 1414648814** [mrtazz/restclient-cpp#60]
in the restclient.cpp, #include "restclient-cpp/version.h",but i can't find the version.h,so that i can't put it to my project...can you help me?

**Comment by mrtazz** [comment]
It's being generated by make when you run it, as per this rule https://github.com/mrtazz/restclient-cpp/blob/master/Makefile.am#L21

**Comment by 1414648814** [comment]
but i meet the another problem,i put your file to my project,it showed the error----


"_curl_easy_cleanup", referenced from:
      RestClient::Connection::~Connection() in connection.o
      RestClient::Connection::~Connection() in librestclient_cpp_la-connection.o
  "_curl_easy_getinfo", referenced from:
      RestClient::Connection::performCurlRequest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in connection.o
      RestClient::Connection::performCurlRequest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in librestclient_cpp_la-connection.o
  "_curl_easy_init", referenced from:
      RestClient::Connection::Connection(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in connection.o
      RestClient::Connection::Connection(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in librestclient_cpp_la-connection.o
  "_curl_easy_perform", referenced from:
      RestClient::Connection::performCurlRequest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in connection.o
      RestClient::Connection::performCurlRequest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in librestclient_cpp_la-connection.o
  "_curl_easy_reset", referenced from:
      RestClient::Connection::performCurlRequest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in connection.o
      RestClient::Connection::performCurlRequest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in librestclient_cpp_la-connection.o
  "_curl_easy_setopt", referenced from:

**Comment by 1414648814** [comment]
my project is run in the mac

**Comment by mrtazz** [comment]
you need to have libcurl installed and link it (https://github.com/mrtazz/restclient-cpp#dependencies)
