### ISSUE TITLE
i don't kown that i should put those the your file to my project

### ISSUE THREAD

**Issue by 1414648814** [mrtazz/restclient-cpp#61]
i don't kown that i should put those the your file to my project, just the .h file, or all file?

**Comment by mrtazz** [comment]
The easiest way might be to build (or [install](https://github.com/mrtazz/restclient-cpp#installation)) the shared library and link it into your project. The [unit tests](https://github.com/mrtazz/restclient-cpp/blob/master/test/test_restclient.cc) should give you an idea of how to use it.
