### ISSUE TITLE
How to check timeout expiration in a rest connection ??

### ISSUE THREAD

**Issue by nabilasalmi** [mrtazz/restclient-cpp#75]
Hello,

I use a multithreaded application where a c++ thread sends some information in a google protocol buffer to a Java thread using RestClient.   I want to initialize a timeout of the Rest connection so that to check expiration timeout in case the Java thread do'nt respond. How to do that ? This is the c++ main code.

```              
                RestClient::init();
		RestClient::Connection* conn = new RestClient::Connection(applicationUrl);
		conn->SetTimeout(5);
		RestClient::HeaderFields headers;
		headers["Accept"] = "application/x-protobuf";
		conn->SetHeaders(headers);
		
                std::string url(applicationUrl);
	        string restRoot((VoiceLayer::getConfigParamValue("REST_ROOT")).c_str());
	        url.append(restRoot);
		string serialized;
	        stvproto::StartEvent event;
                event.set_info(info);
                event.SerializeToString(&serialized);
	
                RestClient::Response r=conn->post(url, serialized); 
                if (r.code==408)
                   cout <<"Request timeout!!" << endl;

```
This code results in a response code=-1 ! What's wrong in my code ?? please help me !
Thank you a lot !

Best regards,
Nabila

**Comment by mrtazz** [comment]
The library is using `28` for the timeout code as this is what libcurl passes up and it's technically not a 408 timeout detected by the server but a client timeout. You can see an example here https://github.com/mrtazz/restclient-cpp/blob/master/test/test_connection.cc#L40
