### ISSUE TITLE
How to put using uploadobject and the  read callback function ?

### ISSUE THREAD

**Issue by renjuzac** [mrtazz/restclient-cpp#77]
Can we have an example in the documentation ? The current documentation says the following :

RestClient::Response RestClient::Connection::put	(const std::string & 	url, const std::string & 	data )		
HTTP PUT method.

Parameters:  url to query, data	HTTP PUT body
Returns response struct

- initialize upload object
- Now specify we want to PUT data
- set read callback function
- set data object to pass to callback function
- set data size

**Comment by mrtazz** [comment]
Can you tell me a little bit more about your use case and why you want to use the uploadObject? It's an implementation detail of the restclient internals and the public API is intentionally made so you pass in the PUT data as a string.

**Comment by renjuzac** [comment]
I was trying to figure out how to PUT a binary file. Any guidance is much appreciated.

**Comment by mrtazz** [comment]
depending on what the receiving server expects, you most likely want to put the base64 encoded string of your binary file as the data parameter. But it's hard to tell without knowing the API endpoint of your server. You will probably have better luck with the API docs of the service you are trying to interact with.
