### ISSUE TITLE
update packages at packagecloud

### ISSUE THREAD

**Issue by felipejfc** [mrtazz/restclient-cpp#82]
Can you include .deb files for updated distros like ubuntu:xenial?

regards

**Comment by mrtazz** [comment]
Sure! The code that pushes packages is [here](https://github.com/mrtazz/restclient-cpp/blob/master/Makefile.packaging.mk#L26). If you want to send a PR, I'm happy to merge it. The `.deb`s that are being pushed are all identical at the moment, so the existing ones should work as well. But please open an issue if something is broken there.
