### ISSUE TITLE
If the url is secured by self-signed certificate and doesn't need to peer verify, it doesn't work.

### ISSUE THREAD

**Issue by chjhaijiang** [mrtazz/restclient-cpp#83]
### Expected behaviour
can't be authenticated.
### Actual behaviour
can be authenticated.
### Environment and debugging details

these 2 option should be enabled in some way.
  curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
  curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

**Comment by mrtazz** [comment]
So far I've gone the way of requiring the OS to be set up with the proper certs to connect instead of allowing to disable cert checking and verification (e.g. [here](https://github.com/mrtazz/restclient-cpp/issues/13)). If this turns out to be a huge problem, I'd be open to revisit that decision.
