### ISSUE TITLE
Cookies in response header

### ISSUE THREAD

**Issue by coolarm** [mrtazz/restclient-cpp#85]
I am able to use this lib for authenticating with username and password set in header. I would like to however, draw the session_key from the response header and use it, thereafter. I see that libcurl supports cookies but I dont see an interface to it in restclient. Has anyone attempted this or what is the alternative to not have to send username/password on every request. Thanks! -

**Comment by mrtazz** [comment]
Is there any reason you can't read those from `RestClient::Response.headers`? Or am I misunderstanding your question?

**Comment by AurelienBallier** [comment]
Cookies / sessions are not set automatically, I don't know if there is an option in the lib for that?

But you can set it manually using : 
```c++
RestClient::Connection* conn = new RestClient::Connection("http://test.com/");

// set headers
RestClient::HeaderFields headers;
headers["Accept"] = "application/json";
headers["Cookie"] = session_cookie;
conn->SetHeaders(headers);
```
Where `session_cookie` is the `Set-Cookie` header returned by the server on authentication process.

**Comment by mrtazz** [comment]
ah ok. Yea there is no way right now to do this automatically. @AurelienBallier's method would be the way to go here.

**Comment by coolarm** [comment]
Thanks for the info. I moved away from cookie-based to digest signature authentication but this snippet should help folks who need to set cookies for prefs.

**Comment by Roman600** [comment]
Except if there is more than one "Set-Cookie" in response, RestClient gets you only the last one. When the first one is exactly what I need.
