### ISSUE TITLE
Will restclient-cpp provide api to manipulate CURL* directly?

### ISSUE THREAD

**Issue by Lw-Cui** [mrtazz/restclient-cpp#89]
Sometimes I need special option like `CURLOPT_FORBID_REUSE` to disable connection reuse. It's too rare to be part of interface API, so I wonder will you add some "raw" API in the future to allow user manipulate handle directly?

**Comment by mrtazz** [comment]
I can't see this being added to restclient-cpp in the near future. A big point is to provide a wrapper that lets you focus on HTTP and not think too much about underlying implementation. This doesn't mean this will never happen, but I won't have time to dedicate to that right now as it's not a priority.
