### ISSUE TITLE
Can`t build unit test 

### ISSUE THREAD

**Issue by alekseibutiaev** [mrtazz/restclient-cpp#94]
/configure --prefix=/home/alexsy/Downloads/restclient-cpp-master/bin --enable-coverage
*******************
mv -f test/.deps/test_program-test_connection.Tpo test/.deps/test_program-test_connection.Po
/bin/bash ./libtool  --tag=CXX   --mode=link g++  -O0 -g -ftest-coverage -fprofile-arcs -Lvendor/gtest-1.7.0/lib/.libs -lgtest  -o test-program vendor/jsoncpp-0.10.5/dist/test_program-jsoncpp.o test/test_program-tests.o test/test_program-test_restclient.o test/test_program-test_connection.o .libs/librestclient-cpp.a -lcurl 
./libtool: line 7486: cd: vendor/gtest-1.7.0/lib/.libs: No such file or directory
libtool:   error: cannot determine absolute directory name of 'vendor/gtest-1.7.0/lib/.libs'
Makefile:530: recipe for target 'test-program' failed
make[2]: *** [test-program] Error 1
make[2]: Leaving directory '/home/alexsy/Downloads/restclient-cpp-master'
Makefile:951: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/alexsy/Downloads/restclient-cpp-master'
Makefile:953: recipe for target 'check' failed
make: *** [check] Error 2

### Environment and debugging details

- compiler and version 
alexsy@aleksei-SW:~$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
- operating system

- libcurl version and compile flags

- full error output of your build as an inline codeblock or gist

(some of these things might not apply but the more you can provide the easier
it will be to fix this bug. Thanks!)

**Comment by mrtazz** [comment]
have you run `./utils/build_gtest.sh` before running the configure script? That shell script is needed to build the test library
