### ISSUE TITLE
undefined symbol: RestClient Connection

### ISSUE THREAD

**Issue by MagnificentPako** [mrtazz/restclient-cpp#98]
### Expected behaviour
It should send a request.

### Actual behaviour
`/usr/local/EmojicodePackages/network-v0/network.so: undefined symbol: _ZN10RestClient10ConnectionC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

### Environment and debugging details

`cmake version 3.10.1`
`ninja 1.8.2`
`clang 5.0.1`
`g++ 7.2.1`

Arch Linux
`libcurl/7.57.0`
not sure how to get the compile flags.

# Additional stuff
The code can be found here: https://github.com/MagnificentPako/emojicode/blob/emojicode-0.5/DefaultPackages/network/network.cpp

And here are the (I believe) relevant parts of the CMake file: https://github.com/MagnificentPako/emojicode/blob/emojicode-0.5/CMakeLists.txt#L45-L46

**Comment by mrtazz** [comment]
How are you installing restclient-cpp? From one of the release packages or building it yourself? What does the compile and linker command line look like in your build?

**Comment by MagnificentPako** [comment]
I installed it using the "restclient-cpp" package in the AUR which didn't seem to export any symbols. Building it myself seems to have fixed it.

**Comment by mrtazz** [comment]
oh interesting! I didn't know this was on AUR :). Glad you like the library and got to fix your problem.
